### ISSUE TITLE
사용자 사전 추가가 안되네요...ㅠ 경로와 관련이 있는건가요?

### ISSUE THREAD

**Issue by bart2001** [Pusnow/mecab-ko-dic-msvc#2]
PS C:\mecab\tools> .\add-userdic-win.ps1
generating userdic...

Remove-Item : 'C:\mecab\tools\mecab-ko-dic' 경로는 존재하지 않으므로 찾을 수 없습니다.
위치 C:\mecab\tools\add-userdic-win.ps1:27 문자:16
Remove-Item <<<<  .\mecab-ko-dic\user-*.csv
CategoryInfo : ObjectNotFound: (C:\mecab\tools\mecab-ko-dic:String) [Remove-Item], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

C:\mecab\mecab-ko-dic\model.def is not a binary model. reopen it as text mode...
reading C:\mecab\user-dic\nnp.csv ...
done!

C:\mecab\mecab-ko-dic\model.def is not a binary model. reopen it as text mode...
reading C:\mecab\user-dic\person.csv ...
done!
C:\mecab\mecab-ko-dic\model.def is not a binary model. reopen it as text mode...
reading C:\mecab\user-dic\place.csv ...
done!
Remove-Item : 'C:\mecab\tools\mecab-ko-dic' 경로는 존재하지 않으므로 찾을 수 없습니다.
위치 C:\mecab\tools\add-userdic-win.ps1:19 문자:16
Remove-Item <<<<  .\mecab-ko-dic\*.bin
CategoryInfo          : ObjectNotFound: (C:\mecab\tools\mecab-ko-dic:String) [Remove-Item], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : 'C:\mecab\tools\mecab-ko-dic' 경로는 존재하지 않으므로 찾을 수 없습니다.
위치 C:\mecab\tools\add-userdic-win.ps1:20 문자:16
Remove-Item <<<<  .\mecab-ko-dic\*.txt
CategoryInfo          : ObjectNotFound: (C:\mecab\tools\mecab-ko-dic:String) [Remove-Item], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
dictionary_compiler.cpp(82) [param.load(DCONF(DICRC))] no such file or directory: mecab-ko-dic\dicrc

**Comment by Pusnow** [comment]
Mecab 경로에서 .\tools\add-userdic-win.ps1 하셔야 합니다

**Comment by Pusnow** [comment]
#3 수정되었습니다.
