### ISSUE TITLE
사용자 사전의 코스트 변경 방법

### ISSUE THREAD

**Issue by Pusnow** [Pusnow/mecab-ko-dic-msvc#4]
리눅스에서는 `make install`을 통하여 사용자 사전의 코스트를 변경할 수 있지만 Windows에서는 이에 대응되는 방법이 없음.

`Powershell`을 이용하여 변경하는 방법 추가 필요.

**Comment by dd199990** [comment]
메일로 문의드렸었는데, Windows에서 대응되는 방법을 못찾아서 
이것저것 하다보니 오류를 이용해서 코스트 비용을 낮췄습니다.

부끄럽지만 제가 사용한 방법을 이야기 드리면
일단 Powershell 이용해서 사용자 사전을 반영 후에, 
C:\mecab\mecab-ko-dic 내의 반영된 사전(ex, user-nng.csv)을 낮은 코스트 값으로 수정합니다.

여기에서 다시 Powershell을 이용해서 수정하면 원래대로 되기 때문에..

저는 R에서 RcppMecab 패키지의 pos 명령의 user_dic을 이용해서
pos(test1, user_dic = "C:\\mecab\\mecab-ko-dic\\user-nng.csv") 실행을 해주고

Powershell 을 이용해서 사용자 사전을 반영해주면  user-nng.csv 는 에러를 일으키고
다른 사전들만 반영됩니다. 그러면서  user-nng.csv  수정한 코스트가 적용됩니다..

불완전한 방법이지만, 일단 코스트 비용이 수정되는 것을 확인하고 사용중이여서 공유합니다..

좋은 방법으로 수정되었으면 좋겠습니다.

**Comment by Pusnow** [comment]
방금 이 케이스를 위한 `compile-win.ps1`을 추가했습니다.

최신 버전을 적용하시고 [링크](https://github.com/Pusnow/mecab-ko-dic-msvc/blob/master/user-dic/README.md)를 참고하셔서 작업해 보시고 문제 있으면 말씀해 주세요.

**Comment by dd199990** [comment]
최신버전 적용 후 compile-win.ps1 작업결과
잘 적용되네요 ^^
빠른 피드백 감사합니다!
